eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # refresh every 5s (default 30s)

spring:
  application:
        name: order-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 30000
        requests.timeout.ms: 15000
        linger.ms: 0
      acks: all

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  observations:
    enable:
      spring:
        kafka: true
logging:
  pattern:
    correlation: "[${spring.application.name:},%mdc{traceId:-},%mdc{spanId:-}]"