eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # refresh every 5s (default 30s)

spring:
  application:
        name: order-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 30000
        requests.timeout.ms: 15000
        linger.ms: 0
      acks: all
