eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # heartbeat every 5s (default 30s)
    lease-expiration-duration-in-seconds: 10  # expired after 10s (default 90s)
spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
            spring.json.trusted.packages: '*'
            spring.json.use.type.headers: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
logging:
  level:
    org.springframework.cache: trace
    com.github.benmanes.caffeine.cache: debug
    org.springframework.data.redis: debug
